### ISSUE TITLE
Deploying TissueMaps: failed to look up user nginx

### ISSUE THREAD

**Issue by jluethi** [TissueMAPS/TissueMAPS#154]
When trying to deploy a new TissueMaps machine, I'm currently running into an issue with the nginx user. Launching the machine works, but during deployment, it fails at the following stage:

`TASK [web-server : Allow web server to read TmUI JS files] *********************************************************************************************************************************************
fatal: [joel_TissueMaps_Testing-standalone-server-001]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "chown failed: failed to look up user nginx", "owner": "root", "path": "/home/tissuemaps/TissueMAPS/tmui/src/build", "size": 4096, "state": "directory", "uid": 0}`
(Working on the current master branch, commit b553411e4cf65bef4bbf8adc03bf9aa1d126c9e6)

It looks like there is an issue with the nginx user & permissions. @riccardomurri I saw that there were recent commits related to the web user (2b0fa14a34e9831cfe2fcf2d37829dc5792c1a5c), so I switched to the master branch from October 11 (882b683bd2253c1031a6e40f9771ca35536ea9e4). There, I get past this issue and fail during TASK [compute : Install package {{ item.desc }}] (see separate issue), so the problem seems to be related to those recent commits.

**Comment by riccardomurri** [comment]
I presume you're installing on Ubuntu, right? Then I do not understand how this problem can happen; in file `tmdeploy/share/playbooks/tissuemaps/roles/web-server/defaults/main.yml` there's the definition:

```yaml
web_user: "{% if ansible_os_family == 'Debian' %}www-data{% else %}nginx{% endif %}"
```

So the playbook should pick up user name `www-data` (which *does* exist on Debian/Ubuntu) instead of `nginx` (which is used on CentOS/RHEL).

**Comment by riccardomurri** [comment]
It looks like the root of the issue is that the "tissuemaps" playbooks do not "gather facts" at the beginning, so `ansible_os_family` may be undefined so `web_user` takes the wrong (default) value.

**Comment by jluethi** [comment]
@riccardomurri Yes, I've been trying to install it on Ubuntu 16

**Comment by jluethi** [comment]
@riccardomurri That commit above didn't fix the problem for me, I still ran into the same issue.

**Comment by jluethi** [comment]
@riccardomurri What's the status of this issue? It would be very useful to be able to deploy new TissueMaps machines again. I want to build a develop-machine for myself, but I'm stuck at this problem

**Comment by riccardomurri** [comment]
I have a fix on my laptop, didn't commit to the main repo yet (would like to clean up before), but I can do it if you're in a hurry.  Or I can build a VM for you.

**Comment by jluethi** [comment]
If you find time at some point this week to push a cleaned-up version, that works for me. If it would take a month, it would be great if you could build a VM for me.

**Comment by riccardomurri** [comment]
@jluethi I just had success in deploying a TM instance with the latest "master" code.  Please let me know if this also works for you so we can close the issue.

**Comment by jluethi** [comment]
Works for me now as well. Thanks a lot for the fix @riccardomurri !
