### ISSUE TITLE
Replacing OpenCV with Pillow in tmclient package

### ISSUE THREAD

**Issue by HackerMD** [TissueMAPS/TissueMAPS#2]
The *tmclient* package currently depends on *OpenCV* (mainly for decoding image formats, such as PNG).

We may want to replace it with *Pillow*. I personally prefer *OpenCV*, but *Pillow* is compatible with setuptools and pip installable, which would facilitate installation.

**Comment by HackerMD** [comment]
I just figured out that OpenCV can now be installed via pip: [opencv-python](https://pypi.python.org/pypi/opencv-python):

```
pip install opencv-python
```

Works like a charm!

**Comment by alecrimi** [comment]
Great! Let's revert to the previous version
