### ISSUE TITLE
not finding existing users v0.1.1 

### ISSUE THREAD

**Issue by alecrimi** [TissueMAPS/TissueMAPS#24]
I am receiving a 502 error for unrecognized users, though the users exists. The problem exists with all users. Even after rebooting the machine, restarting db and other services as uwsgi .
I also have deleted and reinstalled several times tmui.

<img width="1440" alt="screen shot 2017-02-06 at 14 15 07" src="https://cloud.githubusercontent.com/assets/16406658/22648472/2aeb90e4-ec77-11e6-9ec8-6ff83422d53e.png">

![screen shot 2017-02-06 at 14 15 08](https://cloud.githubusercontent.com/assets/16406658/22648480/34131958-ec77-11e6-91d5-f42253fb920b.png)

**Comment by alecrimi** [comment]
Nothing suspicious from  uwsgi.log:
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
worker 9 buried after 1 seconds
worker 10 buried after 1 seconds
worker 11 buried after 1 seconds
worker 12 buried after 1 seconds
worker 13 buried after 1 seconds
worker 14 buried after 1 seconds
worker 15 buried after 1 seconds
worker 16 buried after 1 seconds
goodbye to uWSGI.

**Comment by HackerMD** [comment]
> goodbye to uWSGI

Highly suspicious! This means all server processes got killed and the server is not running!
This explains why you cannot log in.

Try running: `tm_server -vvv`

Something is wrong with your server startup.

**Comment by alecrimi** [comment]
ubuntu@tm-v2:~$ tm_server -vvv
Traceback (most recent call last):
  File "/usr/local/bin/tm_server", line 6, in <module>
    from tmserver.appfactory import create_app
  File "/usr/local/lib/python2.7/dist-packages/tmserver/__init__.py", line 17, in <module>
    import tmserver.serialize
  File "/usr/local/lib/python2.7/dist-packages/tmserver/serialize.py", line 195, in <module>
    @json_encoder(tm.LabelLayer)
AttributeError: 'module' object has no attribute 'LabelLayer'

What the hell?

**Comment by HackerMD** [comment]
I think your `tmlibrary` and `tmserver` packages are not in sync, i.e. not both checked out at release `v0.1.1`. In the latest code of the `master` branch, there is no `LabelLayer` class anymore, but it still exists in `v0.1.1`, see [tmlib.models](https://github.com/TissueMAPS/TmLibrary/blob/877791d8a8e80cba49ee0cec3942b527e3ef5da0/tmlib/models/__init__.py#L62).

**Comment by alecrimi** [comment]
It seems that the version that it can be checked out is the 0.1.0

https://github.com/TissueMAPS/TmServer/blob/master/tmserver/version.py#L16

**Comment by alecrimi** [comment]
The version of tmserver on the branch master is the 0.1.0:

https://github.com/TissueMAPS/TmServer/blob/master/tmserver/version.py#L16
