### ISSUE TITLE
identify_primary_objects_iw module doesn't work

### ISSUE THREAD

**Issue by maffka123** [TissueMAPS/TissueMAPS#25]
As inputs I used smoothed image and thresholded mask

<img width="879" alt="bildschirmfoto 2017-02-10 um 16 05 04" src="https://cloud.githubusercontent.com/assets/19744910/22831642/6805a0b4-efab-11e6-8a55-d76d35ababfb.png">

**Comment by HackerMD** [comment]
This module does not exist in the official [TissueMAPS/jtmodules](https://github.com/TissueMAPS/JtModules/tree/master/src) repository.
