### ISSUE TITLE
Issues with automatic documentation building

### ISSUE THREAD

**Issue by jluethi** [TissueMAPS/TissueMAPS#30]
@HackerMD 

When I rebuild the documentation, I run into the following error message. It complains about not having a module named tmclient.cli. If I remove the tmclient.cli part from the client.rst file, it then fails with the same error later, because it doesn't have tmlib.tools.manager. When I check, tmclient still has a cli.py script, so I don't really understand why it's failing there? Any idea what direction I should search in to solve this?

sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.5.5
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 30 source files that are out of date
updating environment: 30 added, 0 changed, 0 removed
reading sources... [ 36%] tmclient                                                                                                                                                                  
Exception occurred:
  File "/Users/Joel/.virtualenvs/tmaps_release/lib/python2.7/site-packages/sphinxcontrib/autoprogram.py", line 135, in import_object
    raise ImportError("No module named {}".format(module_name))
ImportError: No module named tmclient.cli
The full traceback has been saved in /var/folders/xy/gkzvy_4146v4889pn5z5pb380000gn/T/sphinx-err-SWR8cL.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1

**Comment by HackerMD** [comment]
Are all the package (`tmclient`, `tmlib`, ...) in your Python environment and on your PYTHONPATH?

**Comment by HackerMD** [comment]
Is this fixed?

**Comment by jluethi** [comment]
Yes, issue can be closed, with all the packages installed and on the python path, I can compile the documentation
