### ISSUE TITLE
Improve listing of job IDs in the jterator user interface

### ISSUE THREAD

**Issue by jluethi** [TissueMAPS/TissueMAPS#36]
I noticed that the site IDs don't always start from 1 anymore. For one experiment, they start at 2000 for me and for another one they start at 1600. I'm not sure what's causing this and in principle, it's not a big issue. But if one runs jterator jobs, a site id is required and there is currently no way for the user to know what valid site ids are if they don't start at 1.

Running on a 0.2.2 version private TissueMaps instance & reproduced on current Chimp instance (some 0.2.2rc).

**Comment by HackerMD** [comment]
> I noticed that the site IDs don't always start from 1 anymore.

This has never been the case. When the workflow stage "image_conversion" is resubmitted, new IDs will be assigned to sites. That's expected.

> But if one runs jterator jobs, a site id is required and there is currently no way for the user to know what valid site ids are if they don't start at 1.

Yes, this is not ideal at the moment. The "List jobs" button in the jterator user interface should show the metadata (plate name, well name, etc.) corresponding to each job ID, but this seems to be broken. I will create a separate issue for fixing the UI feature.

**Comment by HackerMD** [comment]
We should probably not expose the actual site IDs, but separate job IDs in the `range(1, len(sites)+1)` which we map internally.

**Comment by jluethi** [comment]
Agree, that sounds like a good solution to the issue!

**Comment by hackermd** [comment]
@jluethi 

I fixed the bug that prevented listing of jobs in the JtUI (TissueMAPS/TmServer@c65d5921834d7f3215c1c796c4c3b7ed7efeeff0). Users can now obtain  job IDs by clicking on the "List jobs" button.

I think mapping the job IDs to the range [1, n] would still be useful, however.

**Comment by hackermd** [comment]
The mapping of job IDs to site IDs has been fixed with TissueMAPS/TmServer@8231848cf96e83b04e345b62c3a542a7ae31b75d
