### ISSUE TITLE
Cannot view list of jterator modules in web interface

### ISSUE THREAD

**Issue by scottberry** [TissueMAPS/TissueMAPS#44]
Recent updates to master branches of JtLibrary and JtModules since v0.3.0 have removed the ability to view the modules in the web interface "Edit Pipeline". v0.3.0 does not suffer this problem

**Comment by hackermd** [comment]
I don't understand. Could you please elaborate?

**Comment by scottberry** [comment]
![screen shot 2017-06-30 at 13 51 35](https://user-images.githubusercontent.com/5407848/27734498-549228a0-5d9b-11e7-816b-8410a9d5a70c.png)

I guess the modules moved to a different path since the release version and they are not not being displayed

**Comment by SaadiaIftikhar** [comment]
I have also the same issue- I have the latest release in the server.  Can not see the list of modules in the browser .

**Comment by hackermd** [comment]
Ok. I know what the problem is. Has to do with the new structure of the `jtmodules` repository. I will revert this change.

Just had a discussion with @riccardomurri about it. We will need to see how we deal with source code of multiple languages in one repository in the future.

**Comment by hackermd** [comment]
The structure of the repository has been reverted back with tissuemaps/jtlibrary@2d13df4cea4ca41354141a2873ea707cdaff679d
