### ISSUE TITLE
z-stack and time info through API

### ISSUE THREAD

**Issue by scottberry** [TissueMAPS/TissueMAPS#54]
Is there a tmclient API function to get the z-stack and time dimensions? get_sites() seems to have only the height (y) and width (x) dimensions of a site. 

In general z- and t- dimensions would be channel-specific.

**Comment by hackermd** [comment]
Sites don't have a time or z dimension. Time point and z-position are accessible via `tpoint` and `zplane` attributes of `SegmentationLayer` and `ChannelLayer` models.
