### ISSUE TITLE
sudo permissions issue (tm_add, start_server, stop_server)

### ISSUE THREAD

**Issue by scottberry** [TissueMAPS/TissueMAPS#61]
tm_add requires sudo rights which the default tissuemaps user no longer has. Yet tm_add is installed for the tissuemaps user rather than the user with sudo rights (e.g. ubuntu user on the Ubuntu system).

Moreover, start_server.sh and stop_server.sh also require sudo rights and should be placed in the home directory of the user with sudo rights rather than the tissuemaps user.

**Comment by scottberry** [comment]
@riccardomurri this is the issue I raised regarding tm_add permissions

**Comment by riccardomurri** [comment]
Fixed by commit https://github.com/TissueMAPS/TmDeploy/commit/5dbb6d8b95ee53a39a4e0bba96d2428f6650daec on TissueMAPS/TmDeploy

**Comment by hackermd** [comment]
I would find it cleaner when tm_user would not perform any sudo tasks. Starting/stopping servers and adding users should be done managed by a privileged user in my opinion. So we could simply install tm_add at a different location that would require root privileges in the first place.

**Comment by riccardomurri** [comment]
> Starting/stopping servers and adding users should be done managed by a privileged user in my opinion.

I agree, but then, to avoid duplication, we would need to install all the TM Python code server-wide in `/usr/local` or similar.  It's quite a change and not something I would attempt on Friday afternoon.

**Comment by hackermd** [comment]
Wouldn't it be sufficient to install (link) the tm_add executable in /usr/local/(s)bin or so?

**Comment by riccardomurri** [comment]
> Wouldn't it be sufficient to install (link) the tm_add executable in /usr/local/(s)bin or so?

Likely not, since the TM libraries are installed in `~tissuemaps/.local/lib`.

**Comment by hackermd** [comment]
Does this work as expected? On an AWS instance based on CentOS 7, I was prompted for a password for the `tissuemaps` user when calling: `sudo tm_add user`.
