### ISSUE TITLE
Merge *all* TM repositories into one?

### ISSUE THREAD

**Issue by riccardomurri** [TissueMAPS/TissueMAPS#62]
TM code is currently scattered across several different code repositories (TmServer, TmUI, TmClient, etc.), with the master "TissueMAPS" repo collecting all of them via Git submodules.

This might be a good setup when different groups of people work on different parts of the code base; however, for a small development group I think this setup is overkill and has a few downsides:

- It is never clear where issues should be reported (on the main repo? on the component that issues the traceback?) and any policy in this respect is going to clash with cross-cutting issues and with users' misreporting

- It makes moving code across components *harder*: what would be a single `git mv file1 file2` becomes a cross-repository operation which leaves no trace in the commit history.

- It makes testing complicated: a pull request on -say- `jtlibrary` needs adjustments on `tm_deploy` to be tested: any issue that spans multiple repositories might end up needing multiple coordinates pull requests, which is a mess.

I would suggest that we merge all code repositories into one.  We can always split later, if the development group grows or we feel the need to split responsibilities in a clear-cut way.

**Comment by riccardomurri** [comment]
cc @sparkvilla @jluethi @scottberry @hackermd

**Comment by jluethi** [comment]
I agree with @riccardomurri on this. While the different repositories offer some nice conceptual separation of independent parts (e.g. client vs. serverside vs. library), it makes it very complicated to commit and test bigger changes, as they almost always involve more than one repository.

**Comment by hackermd** [comment]
Each repository corresponds to a different Python package and these packages are intended to be installed on different machines. Some of them are available on PyPi, while others are not.

While there are some downsides to this approach, I would like to keep it that way.
I would even argue that we should further separate them to make it easier to develop and deploy plugins independently, e.g. jterator modules and interactive analysis tools.

**Comment by hackermd** [comment]
The same holds for server and client side code. They should be separate in my opinion and it enforces the design principles.

**Comment by scottberry** [comment]
I have no opinion on this.

**Comment by sparkvilla** [comment]
I also find it confusing to work with code scattered across multiple repositories. I agree with @riccardomurri, i.e. merging it in a single one would facilitate `testing`, `reporting issue` thus our job as developers. The distinction between the different TM components would still be there, it could be emphasized with more documentation.

**Comment by hackermd** [comment]
Putting everything in one repo breaks the idea of having separate services for a distributed (potentially containerized) application. The `tmserver`, `tmclient` and `tmdeploy` packages are for example all not required in a compute vm/container. Having all packages in one repo will also no longer allow installing packages with pip using the `+git` approach.

**Comment by sparkvilla** [comment]
What about splitting in two groups: 1) `TM client side` containing `tmclient`+`tmdeploy` 2) `TM server side` containing the rest?

**Comment by hackermd** [comment]
Leave the repo structure as it is for now! At least until thesis, publication, etc.

If you then still feel it's a good idea to merge everything into one repo you can do so starting with version > 0.4

**Comment by riccardomurri** [comment]
I'm OK with waiting until thesis is submitted before any change.
Still, let me dot the i's and cross the t's:

> Having all packages in one repo will also no longer allow installing packages with pip using the +git approach.

As far as I can see, TmDeploy right now checks the code out in a
directory, then calls `pip`.  In the unified repo approach, you would
just call `pip` in a subdirectory of the checked out code (as opposed
to running it in the repository root dir).

And even if not checking out code and installing directly from a Git
repo, `pip` has got you covered::

    pip install git+http://...#subdirectory=foo/bar/baz

For details, see: https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support

Repositories are quite orthogonal to Python packaging and deployment
systems.  Repos provide a way to: (1) restrict read/write rights to a
code base, and (2) keep code history separate for different portions
of code.  We don't need (1) and don't want (2) -- at least IMHO.

**Comment by riccardomurri** [comment]
All repos merged into http://github.com/TissueMAPS/TissueMAPS/ after v0.4.1
