### ISSUE TITLE
jterator aggregate features broken

### ISSUE THREAD

**Issue by scottberry** [TissueMAPS/TissueMAPS#64]
Measuring features for aggregated objects is currently producing erroneous results:

In a recent jterator pipeline, I wanted to measure a "nucleus" feature and assign to "cell". I was forced to "aggregate" nuclei into "cells", because rarely once cell contains more than one segmented nucleus (this is a separate issue that need to be addressed). The majority of cells have only one nucleus, so I can recover the features I want from the aggregated dataset by selecting all cells with ```Nuclei_Count... == 1```.

However, when training a classifier using these aggregated features, I found that all cells within a site were assigned the same class. Digging a bit deeper, I downloaded the feature values and found that all "nuclei" within a given site get assigned the same feature value, which is implausible.

Here is an extract (4 cells from each site for a few sites) from the feature-values table and corresponding metadata for one such aggregated feature.

Nuclei_Sum_Intensity_sum_EU_max.rescaled_image  |  Nuclei_Count_EU_max.rescaled_image  |  plate_name  |  well_name  |  well_pos_y  |  well_pos_x  |  tpoint  |  zplane  |  label
------------------------------------------------|--------------------------------------|--------------|-------------|--------------|--------------|----------|----------|-------
445703773                                       |  1                                   |  plate01     |  B02        |  0           |  0           |  0       |  0       |  1
445703773                                       |  1                                   |  plate01     |  B02        |  0           |  0           |  0       |  0       |  2
445703773                                       |  1                                   |  plate01     |  B02        |  0           |  0           |  0       |  0       |  3
445703773                                       |  1                                   |  plate01     |  B02        |  0           |  0           |  0       |  0       |  4
431799932                                       |  1                                   |  plate01     |  B02        |  0           |  1           |  0       |  0       |  1
431799932                                       |  1                                   |  plate01     |  B02        |  0           |  1           |  0       |  0       |  2
431799932                                       |  1                                   |  plate01     |  B02        |  0           |  1           |  0       |  0       |  3
431799932                                       |  1                                   |  plate01     |  B02        |  0           |  1           |  0       |  0       |  4
515482318                                       |  1                                   |  plate01     |  B02        |  0           |  2           |  0       |  0       |  1
515482318                                       |  1                                   |  plate01     |  B02        |  0           |  2           |  0       |  0       |  2
515482318                                       |  1                                   |  plate01     |  B02        |  0           |  2           |  0       |  0       |  3
515482318                                       |  1                                   |  plate01     |  B02        |  0           |  2           |  0       |  0       |  4
319430354                                       |  1                                   |  plate01     |  B02        |  0           |  3           |  0       |  0       |  1
319430354                                       |  1                                   |  plate01     |  B02        |  0           |  3           |  0       |  0       |  2
319430354                                       |  1                                   |  plate01     |  B02        |  0           |  3           |  0       |  0       |  3
319430354                                       |  1                                   |  plate01     |  B02        |  0           |  3           |  0       |  0       |  4
324461400                                       |  1                                   |  plate01     |  B02        |  0           |  4           |  0       |  0       |  1
324461400                                       |  1                                   |  plate01     |  B02        |  0           |  4           |  0       |  0       |  2
324461400                                       |  1                                   |  plate01     |  B02        |  0           |  4           |  0       |  0       |  3
324461400                                       |  1                                   |  plate01     |  B02        |  0           |  4           |  0       |  0       |  4
349542202                                       |  1                                   |  plate01     |  B02        |  0           |  5           |  0       |  0       |  1
349542202                                       |  1                                   |  plate01     |  B02        |  0           |  5           |  0       |  0       |  2
349542202                                       |  1                                   |  plate01     |  B02        |  0           |  5           |  0       |  0       |  3
349542202                                       |  1                                   |  plate01     |  B02        |  0           |  5           |  0       |  0       |  4

**Comment by jluethi** [comment]
Is this specific to the max intensity measurement or general to all intensity measurements for those nuclei?

**Comment by scottberry** [comment]
All intensity and morphology measurements

**Comment by scottberry** [comment]
I guess the problem is somewhere here: https://github.com/TissueMAPS/JtLibrary/blob/master/src/python/jtlib/features.py#L149

**Comment by jluethi** [comment]
Do the measured areas correspond to the sum of all nuclear areas or are they reasonable measurements for one nucleus?
That may help to determine whether the measurement for one nucleus is assigned to all of them or whether the aggregate is made over the whole site.

**Comment by scottberry** [comment]
Nuclei_Sum_Morphology_Area >> Nuclei_Mean_Morphology_Area even when Count =1, so I guess they are getting aggregated by site.

**Comment by scottberry** [comment]
Do either of you have time to fix this bug? @riccardomurri @sparkvilla

**Comment by riccardomurri** [comment]
Not this week, sorry.
​

**Comment by scottberry** [comment]
how about now? Raffa had the same problem on a more recent release.

**Comment by scottberry** [comment]
@riccardomurri @sparkvilla. This is a very serious problem, which prevents us from getting any kind of information about subcellular structures in single cells. It was not broken in previous releases.

**Comment by ragallo** [comment]
Hi guys , how is the fixing of this problem going?

**Comment by riccardomurri** [comment]
I'm not sure I understand how to reproduce the problem.  Can any of you please post code or a step-by-step procedure to producing a table with the wrong values?

**Comment by riccardomurri** [comment]
Tentative patch:

```diff
diff --git a/src/python/jtlib/features.py b/src/python/jtlib/features.py
index 7cb9baf..f70b3a2 100644
--- a/src/python/jtlib/features.py
+++ b/src/python/jtlib/features.py
@@ -175,11 +175,16 @@ class Features(object):
                     for stat in self._aggregate_statistics.keys():
                         values['%s_%s' % (stat, name)].append(np.nan)
             else:
-                index = np.union1d(features.index, labels)
-                diff = len(labels) - len(index)
-                if diff > 0:
-                    logger.warn('%d objects got lost upon aggregation', diff)
-                for name, vals in features.loc[index, :].iteritems():
+                assert np.in1d(labels, features.index), (
+                    "Source objects with ID(s) [{srcs}] appear within"
+                    " area of destination object {dest}"
+                    " but have no associated feature values!"
+                    .format(
+                        dest=ref_label,
+                        srcs=(', '.join(np.setdiff1d(labels, features.index))),
+                    )
+                )
+                for name, vals in features.loc[labels, :].iteritems():
                     if vals.empty:
                         for stat in self._aggregate_statistics.keys:
                             values['%s_%s' % (stat, name)].append(np.nan)
```

**Comment by scottberry** [comment]
This seems to be a fix. Feature-values are now all different between different objects. I have only tested the case where "count = 1" (i.e. aggregation not actually meaningful).

**Comment by riccardomurri** [comment]
@sparkvilla I am going to treat this as a "hotfix" and push to both "develop" and "master" then

**Comment by ragallo** [comment]
I used the module "detect_blobls" to segments some objects, I then label and register those objects. When I try to measure morphology or intensity features it fails and gives the error in the attached screenshot.
![screen shot 2017-11-20 at 17 44 45](https://user-images.githubusercontent.com/25320380/33030203-ffad16ba-ce1a-11e7-83fa-1b4ed5c288ab.jpg)

**Comment by riccardomurri** [comment]
Fixed and committed to both "master" and "develop".

Thanks for testing and reporting, @ragallo !
