### ISSUE TITLE
Default memory configuration too large for SLURM on Ubuntu

### ISSUE THREAD

**Issue by scottberry** [TissueMAPS/TissueMAPS#76]
The current default GC3Pie configuration is for SLURM is 4000MB per core:

```
[resource/cluster]
enabled=yes
type=slurm
frontend=nannygai-slurm-frontend-001
transport=local
auth=noauth
architecture=x86_64
max_cores=40
max_cores_per_job=4
max_memory_per_core=4000 MB
max_walltime=10 days
```

This configuration gets used by many tissuemaps submissions, so that single-core jobs request 4000MB RAM. Overall this results in less jobs running than the total number of compute nodes, since memory requirements cannot be satisfied for 4 concurrently running jobs on a 4-core compute node.

In the case of tool jobs, this memory request gets [multiplied by the number of cores](https://github.com/TissueMAPS/TmLibrary/blob/b1373542c1174cb721cafdd0bf76ffe5f9846f04/tmlib/tools/manager.py#L86) so that they are submitted with ```'--cpus-per-task' '4' '--mem' '16001'```. 

These jobs are then rejected by sbatch.

```
2017-09-20 05:00:58 | ERROR    | gc3.gc3libs                              | Got error in submitting task '11018', informing scheduler: LRMSErro
r: Failed executing command 'cd /home/tissuemaps/.gc3pie_jobs/lrms_job.rtHq9pFcd9 && 'sbatch' '--account' 'sberry' '--no-requeue' '--time' '360
' '--output' 'tool_Heatmap_23_2017-09-20_04-58-50.out' '-e' 'tool_Heatmap_23_2017-09-20_04-58-50.err' '--ntasks' '1' '--cpus-per-task' '4' '--m
em' '16001' '--job-name' 'tool_Heatmap' ./script.7b923d25-66bd-4b43-9510-0ff8e460b2e3.sh' on resource 'cluster'; exit code: 1, stderr: 'sbatch:
 error: Memory specification can not be satisfied
```

Manual configuration to ```max_memory_per_core=3750 MB``` and server restart resolves the issue

**Comment by riccardomurri** [comment]
The pull request above should fix this in all new deployments (once it's merged).

**Comment by scottberry** [comment]
Seems to be fixed
