### ISSUE TITLE
kill workflow (UI and tm_client) not responding

### ISSUE THREAD

**Issue by sparkvilla** [TissueMAPS/TissueMAPS#92]
I tried to use the kill button to kill the workflow from the web-UI but nothing changes. I then tried to use the tm_client as @riccardomurri suggested as:

`tm_client -vv -H 172.23.183.71 -u user -p pass workflow -e test kill`

Still, after 20 minutes I issued the command in the UI nothing happens and on a server side TOP tells me that the TM processes are still runnig. 

As I understand the tmclient is a wrapper around the tmserver. Under tmserver/workflow/api.py there is the function that should do the job:

```
@api.route('/experiments/<experiment_id>/workflow/kill', methods=['POST'])
@jwt_required()
@decode_query_ids('write')
def kill_workflow(experiment_id):
    """
    .. http:post:: /api/experiments/(string:experiment_id)/workflow/kill
        Kill all jobs of the currently running workflow.
        **Example response**:
        .. sourcecode:: http
            HTTP/1.1 200 OK
            Content-Type: application/json
            {
                "message": "ok"
            }
        :reqheader Authorization: JWT token issued by the server
        :statuscode 200: no error
    """
    logger.info('kill workflow for experiment %d', experiment_id)
    workflow = gc3pie.retrieve_most_recent_task(experiment_id, 'workflow')
    gc3pie.kill_task(workflow)
    return jsonify(message='ok')
 ```
Is the gc3pie library that finally should kill the workflow?

**Comment by riccardomurri** [comment]
This should be fixed since v0.4.0
